### ISSUE TITLE
Convert the exportedData to letter columns

### ISSUE THREAD

**Issue by micahcooper** [micahcooper/Excel-Macros#3]
For readability, lets' migrate the rest of the script to use letters for the exportedData column reference.

**Comment by micahcooper** [comment]
@JalenSpringfield Lets finish your review/approval on my current pull request on branch micahcooper-cleanup and then have you start on the script again once merged.

**Comment by JalenSpringfield** [comment]
Do we want both exportedData- and centers- columns to be referred as Strings?

**Comment by micahcooper** [comment]
> Do we want both exportedData- and centers- columns to be referred as Strings?

only the exportedData because that's a human telling the script where to look, but for centersDB, were telling Excel where to put it, and numbers being easier.

**Comment by JalenSpringfield** [comment]
sounds good!
